# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 06:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0007_auto_20171127_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newstopiccomment', to=settings.AUTH_USER_MODEL),
        ),
    ]
