# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 08:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0008_auto_20171127_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchtopic',
            old_name='searchname',
            new_name='search_query',
        ),
    ]
