# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0010_auto_20171128_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newscomment', to='newsapp.Newstopic'),
        ),
    ]
